In [ ]:
!pip install edgartools earningscall

In [ ]:
!pip install notebook-intelligence

In [ ]:
!pip install libsql

In [37]:
import libsql

In [2]:
import numpy as np
import pandas as pd
import yfinance as yf
from edgar import *
from earningscall import get_company
from datetime import datetime,timedelta
import re
from libsql_client import create_client_sync

In [117]:
import libsql
import os
from dotenv import load_dotenv

load_dotenv()

try:
    # Testing the native driver
    conn = libsql.connect(database=os.getenv("TURSO_URL"), auth_token=os.getenv("TURSO_TOKEN"))
    cursor = conn.cursor()
except Exception as e:
    print(f"❌ Environment Error: {e}")

In [ ]:
client.execute('''
    CREATE TABLE IF NOT EXISTS sec_chunks (
        chunk_id TEXT PRIMARY KEY,
        doc_id TEXT,
        ticker TEXT,
        filing_date TEXT,
        item_type TEXT,
        chunk_index INTEGER,
        content TEXT,
        sentiment_score REAL
    )
''')
print("Table 'sec_chunks' is live on Turso.")

In [45]:
set_identity(os.getenv("SEC_API_USER_AGENT"))

In [ ]:
import re

In [ ]:
filings = Company("MSFT").get_filings(form="10-K").latest()
xbrl = filings.xbrl()
statements = xbrl.statements

# Display financial statements
balance_sheet = statements.balance_sheet()
income_statement = statements.income_statement()
cash_flow = statements.cashflow_statement()

In [ ]:
statements

In [ ]:
income_df = income_statement.to_dataframe()

In [ ]:
income_df

In [ ]:
cash_flow = cash_flow.to_dataframe()

In [ ]:
cash_flow

In [ ]:
# balance_sheet = balance_sheet.to_dataframe()
pd.set_option('display.max_rows', 110)  
balance_sheet

In [74]:
company = Company("MSFT")
    # We go back to 2018 to get a full 8 years of historical context
filings = company.get_filings(form="10-Q").latest()

In [99]:
# r = filings.obj()
print(r.filing_date)
fin = r.financials.cash_flow_statement().to_dataframe()
pd.set_option('display.max_rows', None, 'display.max_columns', None)
fin[fin.standard_concept=='NetCashFromOperatingActivities']

2026-01-28

,concept,label,standard_concept,2025-12-31 (Q2),2024-12-31 (Q2),2025-12-31 (YTD),2024-12-31 (YTD),level,abstract,dimension,is_breakdown,dimension_axis,dimension_member,dimension_member_label,dimension_label,balance,weight,preferred_sign,parent_concept,parent_abstract_concept
12,us-gaap_IncreaseDecreaseInOtherNoncurrentAssets,Other long-term assets,NetCashFromOperatingActivities,-1.288000e+09,-1.089000e+09,-1.682000e+09,-2.850000e+09,3,False,False,False,NaN,NaN,NaN,NaN,NaN,-1.0,-1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,us-gaap_IncreaseDecreaseInOperatingCapitalAbst...
17,us-gaap_IncreaseDecreaseInOtherNoncurrentLiabi...,Other long-term liabilities,NetCashFromOperatingActivities,-1.193000e+09,7.160000e+08,-1.670000e+09,6.830000e+08,3,False,False,False,NaN,NaN,NaN,NaN,NaN,1.0,1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,us-gaap_IncreaseDecreaseInOperatingCapitalAbst...
18,us-gaap_NetCashProvidedByUsedInOperatingActivi...,Net cash from operations,NetCashFromOperatingActivities,3.575800e+10,2.229100e+10,8.081500e+10,5.647100e+10,2,False,False,False,NaN,NaN,NaN,NaN,debit,1.0,1.0,us-gaap_CashCashEquivalentsRestrictedCashAndRe...,us-gaap_NetCashProvidedByUsedInOperatingActivi...

In [ ]:
def isolate_q4_safely(raw_df):
    """
    Takes the raw SEC DataFrame and cleanly isolates Q4 for complete years,
    while safely passing through incomplete years (like 2026).
    """
    final_records = []
    
    # Process sequentially by year
    for year in sorted(raw_df['fiscal_year'].unique()):
        year_data = raw_df[raw_df['fiscal_year'] == year]
        
        # 1. Isolate the pieces
        qs = year_data[year_data['fiscal_period'].isin(['Q1', 'Q2', 'Q3'])]
        fy = year_data[year_data['fiscal_period'] == 'FY']
        
        # 2. Always append the standard quarters we have
        for _, row in qs.iterrows():
            final_records.append(row.to_dict())
            
        # 3. The Strict Guardrail for Q4
        # We only calculate Q4 if we have the FY filing AND we have exactly 3 prior quarters.
        if not fy.empty:
            if len(qs) == 3:
                fy_row = fy.iloc[0].copy()
                
                # Flow Metrics Subtraction
                fy_row['revenue'] = fy_row['revenue'] - qs['revenue'].sum()
                fy_row['net_income'] = fy_row['net_income'] - qs['net_income'].sum()
                fy_row['op_cash_flow'] = fy_row['op_cash_flow'] - qs['op_cash_flow'].sum()
                fy_row['capex'] = fy_row['capex'] - qs['capex'].sum()
                
                # Snapshot Metrics (cash_eq, total_liability, etc.) remain untouched
                
                # Update Identifiers
                fy_row['fiscal_period'] = 'Q4'
                fy_row['filing_id'] = fy_row['filing_id'].replace('FY', 'Q4')
                
                final_records.append(fy_row.to_dict())
            else:
                print(f" Alert: FY {year} is missing a Q1/Q2/Q3 filing. Cannot safely calculate Q4.")
        else:
            # This handles 2026 perfectly - it silently ignores Q4 and moves on
            print(f"ℹ Info: FY {year} is incomplete (No 10-K yet). Skipping Q4 calculation.")

    # Convert back to DataFrame and sort chronologically
    clean_df = pd.DataFrame(final_records)
    clean_df = clean_df.sort_values(['fiscal_year', 'fiscal_period'], ascending=[False, False]).reset_index(drop=True)
    
    return clean_df

# Execute the transformation
# final_financials_df = isolate_q4_safely(data)

In [110]:
data.tail(10)

,filing_id,ticker,filing_date,effective_date,fiscal_year,fiscal_period,revenue,net_income,op_cash_flow,capex,cash_eq,total_liability,total_assets,total_equity
19,MSFT_2021_Q3_FILING,MSFT,2021-04-27,2021-04-28,2021,Q3,4.170600e+10,1.545700e+10,2.217900e+10,-5.089000e+09,1.370200e+10,1.743740e+11,3.088790e+11,1.345050e+11
20,MSFT_2021_Q2_FILING,MSFT,2021-01-26,2021-01-27,2021,Q2,4.307600e+10,1.546300e+10,1.251600e+10,-4.174000e+09,1.443200e+10,1.739010e+11,3.041370e+11,1.302360e+11
21,MSFT_2021_Q1_FILING,MSFT,2020-10-27,2020-10-28,2021,Q1,3.715400e+10,1.389300e+10,1.933500e+10,-4.907000e+09,1.720500e+10,1.776090e+11,3.010010e+11,1.233920e+11
22,MSFT_2020_FY_FILING,MSFT,2020-07-30,2020-07-31,2020,FY,1.430150e+11,4.428100e+10,6.067500e+10,-1.544100e+10,1.357600e+10,1.830070e+11,3.013110e+11,1.183040e+11
23,MSFT_2020_Q3_FILING,MSFT,2020-04-29,2020-04-30,2020,Q3,3.502100e+10,1.075200e+10,1.750400e+10,-3.767000e+09,1.171000e+10,1.709480e+11,2.854490e+11,1.145010e+11
24,MSFT_2020_Q2_FILING,MSFT,2020-01-29,2020-01-30,2020,Q2,3.690600e+10,1.164900e+10,1.068000e+10,-3.545000e+09,8.864000e+09,1.726850e+11,2.827940e+11,1.101090e+11
25,MSFT_2020_Q1_FILING,MSFT,2019-10-23,2019-10-24,2020,Q1,3.305500e+10,1.067800e+10,1.381800e+10,-3.385000e+09,1.311700e+10,1.728940e+11,2.789550e+11,1.060610e+11
26,MSFT_2019_FY_FILING,MSFT,2019-08-01,2019-08-02,2019,FY,1.258430e+11,3.924000e+10,5.218500e+10,-1.392500e+10,1.135600e+10,1.842260e+11,2.865560e+11,1.023300e+11
27,MSFT_2019_Q3_FILING,MSFT,2019-04-24,2019-04-25,2019,Q3,3.057100e+10,8.809000e+09,1.352000e+10,-2.565000e+09,1.121200e+10,1.684170e+11,2.632810e+11,9.486400e+10
28,MSFT_2019_Q2_FILING,MSFT,2019-01-30,2019-01-31,2019,Q2,3.247100e+10,8.420000e+09,8.900000e+09,-3.707000e+09,6.638000e+09,1.667310e+11,2.588590e+11,9.212800e+10

In [ ]:

def map_msft_fiscal_metadata(filing_date, form_type):
    """
    filing_date_str: 'YYYY-MM-DD'
    form_type: '10-K' or '10-Q'
    
    Returns: (fiscal_year, fiscal_period)
    """
    month = filing_date.month
    year = filing_date.year
    
    if "10-K" in form_type:
        # 10-K is filed after June 30, belongs to that calendar year
        return year, "FY"
    
    elif "10-Q" in form_type:
        # Microsoft Q1 is filed in Oct/Nov (belongs to NEXT fiscal year)
        if month in [10, 11, 12]:
            return year + 1, "Q1"
        # Microsoft Q2 is filed in Jan/Feb
        elif month in [1, 2, 3]:
            return year, "Q2"
        # Microsoft Q3 is filed in Apr/May
        elif month in [4, 5, 6]:
            return year, "Q3"
            
    return None, None

# Example Usage:
# f_year, f_period = map_msft_fiscal_metadata("2025-10-23", "10-Q")
# Result: (2026, "Q1")

def get_core_financials(ticker="MSFT"):
    """
    Extracts financial metrics from XBRL statements.
    """
    company = Company(ticker)
    # We go back to 2018 to get a full 8 years of historical context
    filings = company.get_filings(form=["10-K", "10-Q"]).filter(filing_date="2019-01-01:")
    raw_data = []
    for filing in filings:
        print(f"Processing {filing.form} filed on {filing.filing_date}...")
        f_year, f_period = map_msft_fiscal_metadata(filing.filing_date, filing.form)            
        f_id = f"{ticker}_{f_year}_{f_period}_FILING"
        effective_date = (filing.filing_date + timedelta(days=1)).strftime('%Y-%m-%d')

        report = filing.obj()

        # 1. Income Statement Data
        income_df = report.financials.income_statement().to_dataframe()
        # We look for the most common XBRL tags (Concepts)
        revenue = income_df[income_df['standard_concept']=='Revenue'].iloc[0, 3]
        net_income = income_df[income_df['standard_concept']=='NetIncome'].iloc[0, 3]

        # 2. Cash Flow Data
        cf_df = report.financials.cashflow_statement().to_dataframe()
        op_cash_flow = cf_df[cf_df['label']=='Net cash from operations'].iloc[0, 3]
        capex = cf_df[cf_df['standard_concept']=='CapitalExpenses'].iloc[0, 3]


        #3. Balance sheet
        bal_df = report.financials.balance_sheet().to_dataframe()
        cash_eq = bal_df[bal_df['standard_concept']=='CashAndMarketableSecurities'].iloc[0, 3]
        tot_assets = bal_df[bal_df['standard_concept']=='Assets'].iloc[0, 3]
        tot_liab = bal_df[bal_df['standard_concept']=='Liabilities'].iloc[0, 3]
        tot_eq = bal_df[bal_df['standard_concept']=='AllEquityBalance'].iloc[0, 3]
        
        raw_data.append({
            'filing_id': f_id,
            'ticker': ticker,
            'filing_date': filing.filing_date,
            'effective_date': effective_date, 
            'fiscal_year': f_year,
            'fiscal_period': f_period,
            "revenue": float(revenue),
            "net_income": float(net_income),
            "op_cash_flow": float(op_cash_flow),
            "capex":float(capex),
            "cash_eq":float(cash_eq),
            "total_liability":float(tot_liab),
            "total_assets":float(tot_assets),
            "total_equity":float(tot_eq)}
        )
    return pd.DataFrame(raw_data)     

data = get_core_financials()

Processing 10-Q filed on 2026-01-28...
Processing 10-Q filed on 2025-10-29...
Processing 10-K filed on 2025-07-30...
Processing 10-Q filed on 2025-04-30...
Processing 10-Q filed on 2025-01-29...
Processing 10-Q filed on 2024-10-30...
Processing 10-K filed on 2024-07-30...
Processing 10-Q filed on 2024-04-25...
Processing 10-Q filed on 2024-01-30...
Processing 10-Q filed on 2023-10-24...
Processing 10-K filed on 2023-07-27...
Processing 10-Q filed on 2023-04-25...
Processing 10-Q filed on 2023-01-24...
Processing 10-Q filed on 2022-10-25...
Processing 10-K filed on 2022-07-28...
Processing 10-Q filed on 2022-04-26...
Processing 10-Q filed on 2022-01-25...
Processing 10-Q filed on 2021-10-26...
Processing 10-K filed on 2021-07-29...
Processing 10-Q filed on 2021-04-27...
Processing 10-Q filed on 2021-01-26...
Processing 10-Q filed on 2020-10-27...
Processing 10-K filed on 2020-07-30...
Processing 10-Q filed on 2020-04-29...
Processing 10-Q filed on 2020-01-29...
Processing 10-Q filed on 2019-10-23...
Processing 10-K filed on 2019-08-01...
Processing 10-Q filed on 2019-04-24...
Processing 10-Q filed on 2019-01-30...

In [114]:
def isolate_q4_safely(raw_df):
    """
    Takes the raw SEC DataFrame and cleanly isolates Q4 for complete years,
    while safely passing through incomplete years (like 2026).
    """
    final_records = []
    
    # Process sequentially by year
    for year in sorted(raw_df['fiscal_year'].unique()):
        year_data = raw_df[raw_df['fiscal_year'] == year]
        
        # 1. Isolate the pieces
        qs = year_data[year_data['fiscal_period'].isin(['Q1', 'Q2', 'Q3'])]
        fy = year_data[year_data['fiscal_period'] == 'FY']
        
        # 2. Always append the standard quarters we have
        for _, row in qs.iterrows():
            final_records.append(row.to_dict())
            
        # 3. The Strict Guardrail for Q4
        # We only calculate Q4 if we have the FY filing AND we have exactly 3 prior quarters.
        if not fy.empty:
            if len(qs) == 3:
                fy_row = fy.iloc[0].copy()
                
                # Flow Metrics Subtraction
                fy_row['revenue'] = fy_row['revenue'] - qs['revenue'].sum()
                fy_row['net_income'] = fy_row['net_income'] - qs['net_income'].sum()
                fy_row['op_cash_flow'] = fy_row['op_cash_flow'] - qs['op_cash_flow'].sum()
                fy_row['capex'] = fy_row['capex'] - qs['capex'].sum()
                
                # Snapshot Metrics (cash_eq, total_liability, etc.) remain untouched
                
                # Update Identifiers
                fy_row['fiscal_period'] = 'Q4'
                fy_row['filing_id'] = fy_row['filing_id'].replace('FY', 'Q4')
                
                final_records.append(fy_row.to_dict())
            else:
                print(f" Alert: FY {year} is missing a Q1/Q2/Q3 filing. Cannot safely calculate Q4.")
        else:
            # This handles 2026 perfectly - it silently ignores Q4 and moves on
            print(f"ℹ Info: FY {year} is incomplete (No 10-K yet). Skipping Q4 calculation.")

    # Convert back to DataFrame and sort chronologically
    clean_df = pd.DataFrame(final_records)
    clean_df['filing_date'] = clean_df['filing_date'].astype(str)
    clean_df['effective_date'] = clean_df['effective_date'].astype(str)
    clean_df = clean_df.sort_values(['fiscal_year', 'fiscal_period'], ascending=[False, False]).reset_index(drop=True)
    
    return clean_df

# Execute the transformation
# final_financials_df = isolate_q4_safely(data)

In [115]:
final = isolate_q4_safely(data)

 Alert: FY 2019 is missing a Q1/Q2/Q3 filing. Cannot safely calculate Q4.
ℹ Info: FY 2026 is incomplete (No 10-K yet). Skipping Q4 calculation.

In [118]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS financial_filings_raw (
    filing_id TEXT PRIMARY KEY,
    ticker TEXT,
    filing_date TEXT,
    effective_date TEXT,
    fiscal_year INTEGER,
    fiscal_period TEXT,
    revenue REAL,
    net_income REAL,
    op_cash_flow REAL,
    capex REAL,
    cash_eq REAL,
    total_liability REAL,
    total_assets REAL,
    total_equity REAL
)
""")
conn.commit()

records_to_insert = final[[
    'filing_id', 'ticker', 'filing_date', 'effective_date', 
    'fiscal_year', 'fiscal_period', 'revenue', 'net_income', 
    'op_cash_flow', 'capex', 'cash_eq', 'total_liability', 
    'total_assets', 'total_equity'
]].values.tolist()

# Execute batch insert
cursor.executemany("""
    INSERT OR REPLACE INTO financial_filings_raw 
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
""", records_to_insert)

conn.commit()
print(f"✅ Successfully staged {len(records_to_insert)} financial quarters into Turso.")

✅ Successfully staged 28 financial quarters into Turso.

In [ ]:
tenk = filings.obj().document
item_1a = tenk.get_section("Item 2")
if item_1a:
    # Note: Section objects also have text() method
    text = item_1a.text(include_tables=False,table_max_col_width=None)
    print(text)

In [ ]:
for f in filings:
    print(f.filing_date.isoformat().replace('-','_'))

# eightk = filings[0].obj()
# print(eightk['Item 1'])
# Get basic information
# report_date = eightk.date_of_report
# items_reported = eightk.items
# print(items_reported)

In [ ]:
'2023-3-3'.replace('-','')

In [ ]:
def clean_prose(text):
    """
    Cleans SEC prose for NLP: Normalizes whitespace and removes boilerplate headers.
    """
    if not text: return ""
    # Normalize whitespace (replaces tabs/newlines with single space)
    text = re.sub(r'\s+', ' ', text)
    # Remove standard SEC 'Table of Contents' and page markers
    text = re.sub(r'(Table of Contents|Item [0-9A-Z]+\.)', '', text, flags=re.IGNORECASE)
    return text.strip()

def get_10k_data(ticker='MSFT',years=5 ):
    company = Company('MSFT')
        # Get the last 5 10-Ks (filing once per year)
    ten_ks = company.get_filings(form="10-K").latest(years)
    data =[]
    for filing in ten_ks:
        
        f_date = filing.filing_date.isoformat()
        doc_id = f"{ticker}_10K_{f_date.replace('-','_')}"
        
        print(f"Processing 10-K filed on: {f_date}")
    
        doc = filing.obj()
        
        # Item 1: Business (Dictionary for RAG)
        raw_biz = doc['Item 1']
        clean_biz = clean_prose(raw_biz) if raw_biz else ""
    
        # Item 1A: Risk Factors (Alpha for NLP)
        raw_risk = doc["Item 1A"]
        clean_risk = clean_prose(raw_risk) if raw_risk else ""
        
        data.append({'doc_id':doc_id,'filing_date':f_date,'item1_biz':clean_biz,'item1a_risk':clean_risk})
        # Atomic Insert: Ensures 10-K data is linked to the date the market saw it
         
    print("10-K Ingestion Complete.")
    return data

In [ ]:
data = get_10k_data()

In [ ]:
def get_10q_data():

In [ ]:
def semantic_sentence_splitter(text, max_chars=1500):
    """Splits 'wall of text' into chunks at sentence boundaries (~350-400 tokens)."""
    if not text: return []
    # Regex split: period/exclamation/question followed by space
    sentences = re.split(r'(?<=[.!?]) +', text)
    chunks, current_chunk = [], ""

    for sentence in sentences:
        if len(current_chunk) + len(sentence) > max_chars and current_chunk:
            chunks.append(current_chunk.strip())
            current_chunk = sentence
        else:
            current_chunk += " " + sentence
    if current_chunk:
        chunks.append(current_chunk.strip())
    return chunks

In [ ]:
def sync_10k_to_turso(data_list, ticker="MSFT"):
    """
    data_list: [{'doc_id': '...', 'item1_biz': '...', 'item1a_risk': '...'}]
    """
    statements = []

    for entry in data_list:
        doc_id = entry['doc_id']
        
        filing_date = entry['filing_date']

        # Define which blobs to process
        sections = [
            ('Item 1', entry['item1_biz']),
            ('Item 1A', entry['item1a_risk'])
        ]

        for item_label, blob in sections:
            chunks = semantic_sentence_splitter(blob)
            
            for i, content in enumerate(chunks):
                # Unique PK: MSFT_20260421_ITEM1A_0
                chunk_id = f"{ticker}_{filing_date}_{item_label.replace(' ', '')}_{i}"
                
                # The SQL statement and its parameters
                sql = """
                INSERT OR REPLACE INTO sec_chunks 
                (chunk_id, doc_id, ticker, filing_date, item_type, chunk_index, content) 
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """
                params = (chunk_id, doc_id, ticker, filing_date, item_label, i, content)
                statements.append((sql, params))

    # 2. Batch upload to Turso (Very efficient over the network)
    if statements:
        print(f"Preparing to sync {len(statements)} chunks to Turso...")
        print("Sample params:", statements[0][1])  
        client.batch(statements)
        print("Done! Data is now in the cloud.")
        
    else:
        print("No data found to sync.")

In [ ]:
sync_10k_to_turso(data)

In [120]:
filing = Company("MSFT").get_filings(form="10-K").latest()
r = filing.obj()

TenK falling back to legacy parser for 'Item7' (filing: 0000950170-25-100235). New parser sections available: ['Item 5', 'Item 10', 'Item 11', 'Item 12', 'Item 13', 'Item 14', 'Item 15', 'Item 16', 'Item 1', 'Item 1A', 'Item 1B', 'Item 1C', 'Item 2', 'Item 3', 'Item 4', 'Item 6', 'Item 7', 'Item 7A', 'Item 8', 'Item 9', 'Item 9A', 'Item 9B', 'Item 9C']. This fallback will be removed in v6.0.

None

In [122]:
with open("./10_K.txt", "w") as file:
    file.write(r['Item 7'])

print()

In [ ]:
r.

"ITEM 1A. RISK FACTORS\n\nOur operations and financial results are subject to various risks and uncertainties, including those described below, that could adversely affect our business, operations, financial condition, results of operations, liquidity, and the trading price of our common stock.\n\nSTRATEGIC AND COMPETITIVE RISKS\n\nWe face intense competition across all markets for our products and services, which could adversely affect our results of operations.\n\nCompetition in the technology sector\n\nOur competitors range in size from diversified global companies with significant research and development resources to small, specialized firms whose narrower product lines may let them be more effective in deploying technical, marketing, and financial resources. Barriers to entry in many of our businesses are low and many of the areas in which we compete evolve rapidly with changing and disruptive technologies, shifting user needs, and frequent introductions of new products and services. If we do not continue to innovate and provide products, devices, and services that appeal to businesses and consumers, we may not remain competitive, which could adversely affect our business, financial condition, and results of operations.\n\nCompetition among platform-based ecosystems\n\nAn important element of our business model has been to create platform-based ecosystems on which many participants can build diverse solutions. A well-established ecosystem creates beneficial network effects among users, application developers, and the platform provider that can accelerate growth. Establishing significant scale in the marketplace is necessary to meet consumer demand and to achieve and maintain attractive margins. We face significant competition from firms that provide competing platforms.\n\n•A competing vertically-integrated model, in which a single firm controls the hardware and software elements of a product and related services, has succeeded with some consumer products such as PCs, tablets, smartphones, gaming consoles, wearables, and other endpoint devices. Competitors pursuing this model also earn revenue from services integrated with the hardware and software platform, including applications and content sold through their integrated marketplaces. They may also be able to claim security and performance benefits from their vertically-integrated offer. We also offer some vertically-integrated hardware and software products and services. Shifting a portion of our business to a vertically-integrated model may increase our cost of revenue and reduce our operating margins.\n\n•We derive substantial revenue from licenses of Windows operating systems on PCs. We face significant competition from competing platforms developed for new devices and form factors such as smartphones and tablets. These devices compete on multiple bases including price and the perceived utility of the device and its platform. Users continue to turn to these devices to perform functions that in the past were performed by PCs. Even if many users view these devices as complementary to a PC, the prevalence of these devices may make it more difficult to attract application developers to our PC operating system platforms. Competing with operating systems licensed at low or no cost may decrease our PC operating system margins. Popular products or services offered on competing platforms could increase their competitive strength. In addition, some of our devices compete with products made by our OEM partners, which may affect their commitment to our platform.\n\n•Competing platforms have content and application marketplaces with scale and significant installed bases. The variety and utility of content and applications available on a platform are important to device purchasing decisions. Users may incur costs to move data and buy new content and applications when switching platforms. To compete, we must successfully enlist developers to write applications for our platform and ensure that these applications have high quality, security, customer appeal, and value. Efforts to compete with competitors’ content and application marketplaces may increase our cost of revenue and lower our operating margins. Competitors’ rules governing their content and applications marketplaces may restrict our ability to distribute products and services through them in accordance with our technical and business model objectives.\n\nFor all of these reasons, we may not be able to compete successfully against our current and future competitors, which could adversely affect our business, operations, financial condition, and results of operations.\n\n  Business model competition\n\nCompanies compete with us based on a growing variety of business models.\n\n•A material part of our business involves cloud-based services available across the spectrum of computing devices. We and our competitors continue to devote significant resources to developing and deploying cloud-based strategies and services for consumers and business customers, and pricing and delivery models are evolving. \n\n•We are investing in artificial intelligence (“AI”) across the entire company and infusing generative AI capabilities into our consumer and commercial offerings. AI technology and services are a highly competitive and rapidly evolving market, and new competitors continue to enter the market. We will bear significant development and operational costs to build and support the AI models, services, platforms, and infrastructure necessary to meet the needs of our customers. To compete effectively we must also be responsive to technological change, new and potential regulatory developments, and public scrutiny.\n\n•Even as we transition more of our business to infrastructure-, platform-, and software-as-a-service business models, the license-based proprietary software model generates a substantial portion of our software revenue. We bear the costs of converting original ideas into software products through investments in research and development, offsetting these costs with the revenue received from licensing our products. Many of our competitors also develop and sell software to businesses and consumers under this model.\n\n•Other competitors develop and offer free applications, online services, and content, and make money by selling third-party advertising. Advertising revenue funds development of products and services these competitors provide to users at little or no cost, competing directly with our revenue-generating products.\n\n•Some companies compete with us by modifying and then distributing open source software at little or no cost to end users, developing, making available, or using AI models that are open, and earning revenue on advertising or integrated products and services. These firms do not bear the full costs of research and development for the open source products. Some open source products mimic the features and functionality of our products.\n\nThe competitive pressures described above may cause decreased sales volumes, price reductions, and/or increased operating costs, such as for research and development, marketing, and sales incentives, which could adversely affect our financial condition and results of operations.\n\nOur focus on cloud-based and AI services presents execution and competitive risks. We are incurring significant costs to build and maintain infrastructure to support cloud-based and AI services, reducing operating margins. Whether we succeed in cloud-based and AI services depends on our execution in several areas, including:\n\n•Continuing to bring to market compelling cloud-based and AI services and products that generate increasing traffic and market share.\n\n•Maintaining the utility, compatibility, and performance of our cloud-based and AI services on the growing array of computing devices, including PCs, smartphones, tablets, gaming consoles, and other devices.\n\n•Continuing to enhance the attractiveness of our cloud platforms to third-party developers.\n\n•Ensuring our cloud-based services meet the reliability expectations and specific requirements of our customers and maintain the security of their data as well as help them meet their own compliance needs.\n\n•Making our suite of cloud-based services platform-agnostic, available on a wide range of devices and ecosystems, including those of our competitors.\n\nIt is uncertain whether our strategies will continue to attract users or generate the revenue required to succeed. If we are not effective in executing organizational and technical changes to increase efficiency and accelerate innovation, or if we fail to generate sufficient usage of our new products and services, we may not grow revenue in line with the infrastructure and development investments described above. This could adversely affect our operations, financial condition, and results of operations.\n\n  Our AI systems offer users powerful tools and capabilities. However, there may be instances where these systems are used in ways that are unintended or inappropriate. In addition, some users may also engage in fraudulent or abusive activities through our cloud-based and AI services, such as unauthorized account access, payment fraud, or terms of service violations including cryptocurrency mining or launching cyberattacks. While we are committed to detecting and controlling such misuse of our cloud-based and AI services, our efforts may not be effective, and we may incur reputational damage or experience adverse impacts to our business and results of operations.\n\nRISKS RELATING TO THE EVOLUTION OF OUR BUSINESS\n\nWe make significant investments in products and services that may not achieve expected returns. We will continue to make significant investments in research, development, and marketing for existing products, services, and technologies, including AI-based products and services. We also invest in the development and acquisition of a variety of hardware for productivity, communication, and entertainment, including PCs, tablets, and gaming devices. Investments in new technology are speculative. Commercial success depends on many factors, including innovation, developer support, and effective distribution and marketing. If customers do not perceive our latest offerings as providing significant new functionality or other value, they may reduce their purchases of new software and hardware products or upgrades, unfavorably affecting revenue. We may not achieve significant revenue from new product, service, and distribution channel investments for several years, if at all. New products and services may not be profitable or may not achieve operating margins as high as we have experienced historically. We may not get engagement in certain features that drive post-sale monetization opportunities. Our data-handling practices across our products and services will continue to be under scrutiny. Perceptions of mismanagement, driven by regulatory activity or negative public reaction to our practices or product experiences, could negatively impact product and feature adoption. Developing new technologies is complex. It can require long development and testing periods. We could experience significant delays in new releases or significant problems in creating new products or services. These factors could adversely affect our business, financial condition, and results of operations. \n\nAcquisitions, joint ventures, and strategic alliances could have an adverse effect on our business. We expect to continue making acquisitions and entering into joint ventures and strategic alliances as part of our long-term business strategy. For example, in October 2023 we completed our acquisition of Activision Blizzard, Inc. (“Activision Blizzard”). In January 2023 we announced the third phase of our OpenAI strategic partnership. Acquisitions and other transactions and arrangements involve significant challenges and risks, including that they do not advance our business strategy, that we get an unsatisfactory return on our investment, that they raise new compliance-related obligations and challenges, that we have difficulty integrating and retaining new employees, business systems, and technology, that they distract management from our other businesses, or that announced transactions may not be completed. If an arrangement fails to adequately anticipate changing circumstances and interests of a party, it may result in early termination or renegotiation of the arrangement. We also have limited ability to control or influence third parties with whom we have arrangements, which may impact our ability to realize the anticipated benefits. The success of these transactions and arrangements depend in part on our ability to leverage them to enhance our existing products and services or develop compelling new ones, as well as the acquired companies’ ability to meet our policies and processes in areas such as data governance, privacy, digital safety, responsible AI, and cybersecurity. It may take longer than expected to realize the full economic benefits from these transactions and arrangements, such as increased revenue or enhanced efficiencies, or the benefits may ultimately be smaller than we expected, which could cause an impairment of goodwill or intangibles. We have recorded, and may in the future be required to record, a significant charge in our consolidated financial statements during the period in which any impairment of our goodwill or amortizable intangible assets is determined, negatively affecting our results of operations. In addition, an acquisition may be subject to challenge even after it has been completed. These events could adversely affect our business, operations, financial condition, and results of operations.\n\n  CYBERSECURITY, DATA PRIVACY, AND PLATFORM ABUSE RISKS\n\nCyberattacks and security vulnerabilities could lead to reduced revenue, increased costs, liability claims, or harm to our reputation or competitive position.\n\nSecurity of our information technology\n\nThreats to security can take a variety of forms. Threat actors, including individual and groups of hackers and sophisticated organizations, including nation-states, state-sponsored organizations, or cybercriminal groups, continuously undertake attacks that pose threats to our customers and our internal infrastructure, and we have experienced cybersecurity incidents in which such actors have gained unauthorized access to our systems and data, including customer systems and data. These actors use a wide variety of methods, which include developing and deploying malicious software; exploiting known and potential vulnerabilities or intentionally designed processes in our or third-party hardware, software, or other infrastructure to attack our products and services or gain access to our networks and datacenters; using social engineering techniques to induce our employees, users, partners, or customers to disclose sensitive information, such as passwords, or take other actions to gain access to our data or our users’ or customers’ data; or acting in a coordinated manner or conducting coordinated attacks. For example, as previously disclosed in our Form 8-K filed with the Securities and Exchange Commission on January 19, 2024 and amended on March 8, 2024, beginning in late November 2023, a nation-state associated threat actor used a password spray attack to compromise a legacy test account and, in turn, gain access to Microsoft email accounts. The threat actor used information it obtained to gain unauthorized access to some of our source code repositories and internal systems, and the threat actor could continue to utilize this and other information to attempt to gain access to our systems or otherwise adversely affect our business and results of operations. This incident has and may continue to result in harm to our reputation and customer relationships. Nation-state and state-sponsored actors can sustain malicious activities for extended periods and deploy significant resources to plan and carry out attacks. Nation-state attacks against us, our customers, or our partners have and may continue to intensify due to our transparency to our customers, other stakeholders, and the public about cyberattacks, and during elections or periods of intense diplomatic or armed conflict. Challenges or failures in applying security patches to all hardware and devices connected to our systems, including end-of-life and end-of-support equipment, have and may continue to result in unauthorized access to our systems and data in the future. Cyber incidents and attacks, individually or in the aggregate, could adversely affect our financial condition, results of operations, competitive position, and reputation, or expose us to legal or regulatory risk.\n\nInadequate account security or organizational security practices, including those of companies we have acquired or those of the third parties we utilize, have resulted and may result in unauthorized access to our systems and data, including customer systems and data. For example, passwords may not be rotated and employee access may not be updated or removed on a timely basis. Employees or third parties may intentionally compromise our or our users’ security or systems or reveal confidential information, and laws in foreign jurisdictions may compel actions by such parties against our interests and could limit our recourse. Malicious actors may employ the supply chain to introduce malware through software updates or compromised supplier accounts or hardware.\n\nCyberthreats are constantly evolving and becoming increasingly sophisticated and complex, increasing the difficulty of detecting and successfully defending against them. Threat actors may also utilize emerging technologies, such as AI and machine learning. Our current capabilities may not detect certain vulnerabilities or new attack methods, which may allow them to persist in the environment over long periods of time. It may be difficult to determine the best way to investigate, mitigate, contain, and remediate the harm caused by a cyber incident. Such efforts may not be successful, and we may make errors or fail to take necessary actions. It is possible that threat actors may gain undetected access to other networks and systems after establishing a foothold on an internal system. Cyber incidents and attacks can have cascading impacts that unfold with increasing speed across our internal networks and systems, as well as those of our partners and customers. In addition, it may take considerable time for us to investigate and evaluate the full impact of incidents, particularly for sophisticated attacks. As a result of these and other factors, we may not be able to provide prompt, full, and reliable information about the incident to our customers, partners, regulators, and the public. Breaches of our facilities, network, or data security can disrupt the security of our systems and business applications, impair our ability to provide services to our customers and protect the privacy of their data, result in product development delays, compromise confidential or technical business information, result in theft or misuse of our intellectual property or other assets, subject us to ransomware attacks, require us to allocate more resources to improve technologies or remediate the impacts of attacks, or otherwise adversely affect our business. In addition, actions taken to remediate an incident could result in outages, data losses, and disruptions of our services.\n\n  Our internal environment continues to evolve. Often, we are early adopters of new devices and technologies. We embrace new ways of sharing data and communicating internally and with partners and customers using methods such as social networking and other consumer-oriented technologies. Increasing use of generative AI models in our internal systems may create new attack surfac

In [141]:
import re

import re

def clean_mda_narrative(raw_text):
    if not raw_text: return ""
    text = raw_text.replace('\r\n', '\n')
    paragraphs = re.split(r'\n{2,}', text)
    clean_paragraphs = []

    # Expanded blacklist for common 10-K/10-Q artifacts
    debris_blacklist = {
        'three months ended', 'six months ended', 'nine months ended', 'year ended',
        'percentage change', 'percentage', 'change', 'in millions', 'in billions',
        'unaudited', 'consolidated statements', 'revenue', 'gross margin',
        'operating income', 'total', 'total revenue', 'december 31,', 'march 31,', 
        'june 30,', 'september 30,', 'as a percent of revenue', 'percentagechange',
        'net income', 'operating expenses', 'cost of revenue'
    }

    for p in paragraphs:
        lines = p.split('\n')
        surviving_lines = []

        for line in lines:
            line_str = line.strip()
            if not line_str: continue
            
            # 1. Blacklist Check
            if line_str.lower() in debris_blacklist: continue

            # 2. Footnote & Boilerplate Check
            if line_str.startswith('(a)') or line_str.startswith('(b)') or 'Refer to Note' in line_str:
                continue
                
            # 3. The "Ghost Table" Word Count Check (KILLS ROW HEADERS)
            # A real sentence has more than 4 words. 
            words = line_str.split()
            if len(words) < 5:
                continue

            # 4. The Density Test (KILLS NUMBERS/SYMBOLS)
            total_chars = len(line_str)
            alpha_chars = sum(c.isalpha() for c in line_str)
            if total_chars > 0 and (alpha_chars / total_chars) < 0.5:
                continue 

            surviving_lines.append(line_str)

        if surviving_lines:
            clean_paragraphs.append(" ".join(surviving_lines))

    return "\n\n".join(clean_paragraphs)


def semantic_sentence_splitter(text, max_chars=1200):
    """Splits text into RAG-friendly chunks at sentence boundaries."""
    if not text: return []
    sentences = re.split(r'(?<=[.!?]) +', text)
    chunks, current_chunk = [], ""

    for sentence in sentences:
        if len(current_chunk) + len(sentence) > max_chars and current_chunk:
            chunks.append(current_chunk.strip())
            current_chunk = sentence
        else:
            current_chunk += " " + sentence
    if current_chunk:
        chunks.append(current_chunk.strip())
    return chunks

In [151]:
def clean_mda_narrative(raw_text):
    """
    Cleans SEC MD&A text by evaporating fragmented table rows using 
    alphabetic density and word-count thresholds, preserving narrative context.
    """
    if not raw_text: return ""

    # 1. Standardize line breaks and split
    lines = raw_text.replace('\r\n', '\n').split('\n')
    clean_lines = []

    # 2. Blacklist of orphaned table row headers and SEC boilerplate
    debris_blacklist = {
        'three months ended', 'six months ended', 'nine months ended', 'year ended',
        'percentage change', 'in millions', 'in billions', 'unaudited',
        'consolidated statements', 'total revenue', 'gross margin',
        'operating income', 'net income', 'operating expenses', 'cost of revenue',
        'as a percent of revenue', 'percentagechange', 'diluted earnings per share'
    }

    # Regex to catch dynamic headers like "Fiscal Year 2025 Compared with 2024"
    comparison_header_regex = r'(?:Fiscal Year|Three Months Ended|Six Months Ended).*?Compared with'

    for line in lines:
        line_str = line.strip()
        
        # Preserve natural paragraph spacing
        if not line_str:
            clean_lines.append("")
            continue

        # Filter A: Is it known table debris?
        if line_str.lower() in debris_blacklist: 
            continue
            
        # Filter B: Is it a repeating comparative header?
        if re.search(comparison_header_regex, line_str, re.IGNORECASE):
            continue

        # Filter C: The "Table Cell" Density Test
        # Real sentences are mostly letters. Table cells are mostly numbers/symbols.
        total_chars = len(line_str)
        alpha_chars = sum(c.isalpha() for c in line_str)
        if total_chars > 0 and (alpha_chars / total_chars) < 0.5:
            continue # Drops lines like "$ 81,273" or "17%"

        # Filter D: The "Ghost Table Row" Check
        # Executives don't write 3-word sentences in an MD&A. 
        # If it's short, it's an orphaned table row label.
        if len(line_str.split()) < 5:
            continue

        # If it survives all filters, it is high-value narrative.
        clean_lines.append(line_str)

    # Re-join into a document
    text = "\n".join(clean_lines)
    
    # Snap the massive gaps (where tables used to be) back into clean double-newlines
    text = re.sub(r'\n{3,}', '\n\n', text).strip()

    return text

In [144]:
with open("./10_K.txt", "w") as file:
    file.write(clean_mda_narrative(r['Item 7']))

In [148]:
with open('./10_K_raw.text','w') as f:
          f.write(r.management_discussion)

In [152]:
def isolate_alpha_chapters(raw_mda_text):
    """
    Ruthlessly slices the MD&A, keeping only the high-value volatility drivers
    and dropping the glossary, taxes, and accounting boilerplate.
    """
    if not raw_mda_text:
        return ""
        
    # The sections that actually move the stock price
    target_headers = [
        r'Economic Conditions, Challenges, and Risks',
        r'Fiscal Year \d{4} Compared with Fiscal Year \d{4}',
        r'Reportable Segments',
        r'Other Planned Uses of Capital'
    ]
    
    # The sections that waste model compute
    stop_headers = [
        r'Metrics',                   # Kills the glossary
        r'OTHER INCOME \(EXPENSE\)',  # Kills derivative hedging talk
        r'INCOME TAXES',              # Kills IRS/tax legislation talk
        r'CRITICAL ACCOUNTING ESTIMATES', # Kills accounting theory
        r'STATEMENT OF MANAGEMENT'    # Kills signatures
    ]
    
    target_regex = re.compile("|".join(target_headers), re.IGNORECASE)
    stop_regex = re.compile("|".join(stop_headers), re.IGNORECASE)
    
    lines = raw_mda_text.replace('\r\n', '\n').split('\n')
    extracted_chapters = []
    is_reading = False
    
    for line in lines:
        line_str = line.strip()
        if not line_str:
            continue
            
        # Toggle ON if we hit a high-value header
        if target_regex.search(line_str):
            is_reading = True
            
        # Toggle OFF if we hit regulatory noise
        if stop_regex.search(line_str):
            is_reading = False
            
        if is_reading:
            extracted_chapters.append(line_str)
            
    return "\n".join(extracted_chapters)

In [160]:
routed=isolate_alpha_chapters(r.management_discussion)
clean = clean_mda_narrative(routed)
with open("./10_K_clean.txt", "w") as file:
    file.write(clean)

# filings.obj()['Item 2']

In [ ]:
print(clean_mda_narrative(r['Item 7']))

In [159]:
clean

"•Microsoft Cloud revenue increased 23% to $168.9 billion.\n•Microsoft 365 Commercial products and cloud services revenue increased 14% driven by Microsoft 365 Commercial cloud revenue growth of 15%.\n•Microsoft 365 Consumer products and cloud services revenue increased 11% driven by Microsoft 365 Consumer cloud revenue growth of 11%.\n•Dynamics products and cloud services revenue increased 15% driven by Dynamics 365 revenue growth of 19%.\n•Server products and cloud services revenue increased 23% driven by Azure and other cloud services revenue growth of 34%.\n•Windows OEM and Devices revenue increased 3%.\n•Xbox content and services revenue increased 16%.\n•Search and news advertising revenue excluding traffic acquisition costs increased 20%.\nOur industry is dynamic and highly competitive, with frequent changes in both technologies and business models. Each industry shift is an opportunity to conceive new products, new technologies, or new ideas that can further transform the industry and our business. At Microsoft, we push the boundaries of what is possible through a broad range of research and development activities that seek to identify and address the changing demands of customers and users, industry trends, and competitive forces.\nMicrosoft and OpenAI maintain a long-term strategic partnership originally established in 2019. Microsoft is a major investor in OpenAI, and the companies have reciprocal revenue-sharing arrangements. We hold rights to OpenAI’s intellectual property, including models and infrastructure, for integration into our products. The OpenAI API is exclusive to Azure, runs on Azure, and is available through the Azure OpenAI Service. We also have a right of first refusal on OpenAI's new capacity needs.\nEconomic Conditions, Challenges, and Risks\nThe markets for software, devices, and cloud-based services are dynamic and highly competitive. Our competitors are developing new software and devices, while also deploying competing cloud-based services for consumers and businesses. The devices and form factors customers prefer evolve rapidly, influencing how users access services in the cloud and, in some cases, the user’s choice of which suite of cloud-based services to use. Aggregate demand for our software, services, and devices is also correlated to global macroeconomic and geopolitical factors, which remain dynamic. We must continue to evolve and adapt over an extended time in pace with this changing environment.\nThe investments we are making in cloud and AI infrastructure and devices will continue to increase our operating costs and may decrease our operating margins. We continue to identify and evaluate opportunities to expand our datacenter locations and increase our server capacity to meet the evolving needs of our customers, particularly given the growing demand for AI services. Our datacenters depend on the availability of permitted and buildable land, predictable energy, networking supplies, and servers, including graphics processing units (“GPUs”) and other components. Our devices are primarily manufactured by third-party contract manufacturers. For the majority of our products, we have the ability to use other manufacturers if a current vendor becomes unavailable or unable to meet our requirements. However, some of our products contain certain components for which there are very few qualified suppliers. Extended disruptions at these suppliers could impact our ability to manufacture devices on time to meet consumer demand.\nOur success is highly dependent on our ability to attract and retain qualified employees. We hire a mix of university and industry talent worldwide. We compete for talented individuals globally by offering an exceptional working environment, broad customer reach, scale in resources, the ability to grow one’s career across many different products and businesses, and competitive compensation and benefits.\nOur international operations provide a significant portion of our total revenue and expenses. Many of these revenue and expenses are denominated in currencies other than the U.S. dollar. As a result, changes in foreign exchange rates may significantly affect revenue and expenses. Fluctuations in the U.S. dollar relative to certain foreign currencies did not have a material impact on reported revenue and expenses from our international operations in fiscal year 2025.\nFurther, global, regional, and local economic developments and changes in global trade policies such as restrictions on international trade, including tariffs and other controls on imports or exports, could result in increased supply chain challenges, cost volatility, and consumer and economic uncertainty which may adversely affect our results of operations.\nRefer to Risk Factors (Part I, Item 1A of this Form 10-K) for a discussion of these factors and other risks.\nOur revenue fluctuates quarterly and is generally higher in the fourth quarter of our fiscal year. Fourth quarter revenue is driven by a higher volume of multi-year contracts executed during the period.\nWe report our financial performance based on the following segments: Productivity and Business Processes, Intelligent Cloud, and More Personal Computing. The segment amounts included in MD&A are presented on a basis consistent with our internal management reporting.\nIn August 2024, we announced changes to the composition of our segments. These changes align our segments with how we currently manage our business, most notably bringing the commercial components of Microsoft 365 together in the Productivity and Business Processes segment. Beginning in fiscal year 2025, the information that our chief operating decision maker is regularly provided and reviews for purposes of allocating resources and assessing performance reflects these segment changes. Prior period segment information has been recast to conform to the way we internally manage and monitor our business during fiscal year 2025.\nAdditional information on our reportable segments is contained in Note 18 – Segment Information and Geographic Data of the Notes to Financial Statements (Part II, Item 8 of this Form 10-K).\nRevenue increased $36.6 billion or 15% with growth across each of our segments. Intelligent Cloud revenue increased driven by Azure. Productivity and Business Processes revenue increased driven by Microsoft 365 Commercial cloud. More Personal Computing revenue increased driven by Gaming and Search and news advertising.\nCost of revenue increased $13.7 billion or 19% driven by growth in Microsoft Cloud.\nGross margin increased $22.9 billion or 13% with growth across each of our segments.\n•Gross margin percentage decreased slightly driven by Intelligent Cloud, offset in part by More Personal Computing.\n•Microsoft Cloud gross margin percentage decreased to 69% driven by the impact of scaling our AI infrastructure, offset in part by efficiency gains in Azure.\nOperating expenses increased $3.8 billion or 6% driven by investments in cloud and AI engineering and Gaming, including the impact of the Activision Blizzard acquisition.\nOperating income increased $19.1 billion or 17% with growth across each of our segments.\nRevenue increased $14.0 billion or 13%.\n•Microsoft 365 Commercial products and cloud services revenue increased $10.8 billion or 14%. Microsoft 365 Commercial cloud revenue grew 15% with Microsoft 365 Commercial seat growth of 6% driven by small and medium businesses and frontline worker offerings, as well as growth in revenue per user. Microsoft 365 Commercial products revenue grew 7% driven by the Windows Commercial on-premises components of Microsoft 365 suite sales and an increase in Office transactional purchasing with the launch of Office 2024.\n•Microsoft 365 Consumer products and cloud services revenue increased $756 million or 11%. Microsoft 365 Consumer cloud revenue grew 11% driven by Microsoft 365 Consumer subscriber growth of 8% to 89.0 million, as well as growth in revenue per user from the price increase announced in January 2025.\n•LinkedIn revenue increased $1.4 billion or 9% with growth across all lines of business.\n•Dynamics products and cloud services revenue increased $996 million or 15% driven by growth in Dynamics 365, offset in part by a decline in Dynamics on-premises products. Dynamics 365 revenue grew 19% with growth across all workloads.\nOperating income increased $10.1 billion or 17%.\n•Cost of revenue increased $2.8 billion or 14% driven by growth in Microsoft 365 Commercial cloud.\n•Gross margin increased $11.2 billion or 13% driven by growth in Microsoft 365 Commercial cloud. Gross margin percentage decreased slightly primarily driven by the impact of scaling our AI infrastructure, offset in part by efficiency gains in Microsoft 365 Commercial cloud.\n•Operating expenses increased $1.1 billion or 4% driven by investments in cloud and AI engineering and commercial sales.\nRevenue increased $18.8 billion or 21%.\n•Server products and cloud services revenue increased $18.6 billion or 23% driven by Azure and other cloud services. Azure and other cloud services revenue grew 34% driven by demand for our portfolio of services. Server products revenue decreased 3% driven by a decrease in transactional purchasing with continued customer shift to cloud offerings.\n•Enterprise and partner services revenue increased $166 million or 2% driven by growth in Enterprise Support Services, offset in part by a decline in Industry Solutions.\nOperating income increased $6.8 billion or 18%.\n•Cost of revenue increased $10.6 billion or 36% driven by growth in Azure.\n•Gross margin increased $8.2 billion or 14% driven by growth in Azure. Gross margin percentage decreased driven by the impact of scaling our AI infrastructure, offset in part by efficiency gains in Azure.\n•Operating expenses increased $1.5 billion or 7% driven by investments in cloud and AI engineering.\nRevenue increased $3.8 billion or 7%.\n•Windows and Devices revenue increased $288 million or 2%. Windows OEM and Devices revenue increased 3% driven by growth in Windows OEM, offset in part by a decline in Devices.\n•Gaming revenue increased $2.0 billion or 9% driven by growth in Xbox content and services, offset in part by a decline in Xbox hardware. Xbox content and services revenue increased 16% driven by the impact of the Activision Blizzard acquisition and Xbox Game Pass. Xbox hardware revenue decreased 25% driven by lower volume of consoles sold.\n•Search and news advertising revenue increased $1.6 billion or 13%. Search and news advertising revenue excluding traffic acquisition costs increased 20% driven by higher search volume and higher revenue per search.\nOperating income increased $2.2 billion or 18%.\n•Cost of revenue increased $346 million or 1% driven by growth in Search and news advertising.\n•Gross margin increased $3.5 billion or 13% with growth across all businesses. Gross margin percentage increased with improvement across all businesses.\n•Operating expenses increased $1.3 billion or 9% driven by Gaming, including the impact of the Activision Blizzard acquisition.\nResearch and development expenses include payroll, employee benefits, stock-based compensation expense, and other headcount-related expenses associated with product development. Research and development expenses also include technology development costs, including AI training and other infrastructure costs, third-party development and programming costs, and the amortization of purchased software code and services content.\nResearch and development expenses increased $3.0 billion or 10% driven by investments in cloud and AI engineering and Gaming, including the impact of the Activision Blizzard acquisition.\nSales and marketing expenses include payroll, employee benefits, stock-based compensation expense, and other headcount-related expenses associated with sales and marketing personnel, and the costs of advertising, promotions, trade shows, seminars, and other programs.\nSales and marketing expenses increased $1.2 billion or 5% driven by investments in commercial sales and Gaming, including the impact of the Activision Blizzard acquisition.\nGeneral and administrative expenses include payroll, employee benefits, stock-based compensation expense, employee severance expense incurred as part of a corporate program, and other headcount-related expenses associated with finance, legal, facilities, certain human resources and other administrative personnel, certain taxes, and legal and other administrative fees.\nGeneral and administrative expenses decreased $386 million or 5% driven by Gaming, including the impact of the Activision Blizzard acquisition.\nInterest and dividends income decreased primarily due to lower portfolio balances. Interest expense decreased primarily due to maturities of commercial paper and higher capitalization of debt interest expense, offset in part by higher finance lease interest expense. Net recognized losses on investments increased primarily due to higher impairments, offset in part by higher gains on equity investments in the current period. Net losses on derivatives increased primarily due to higher losses on equity derivatives in the current period. Other, net primarily reflects net recognized losses on equity method investments, including OpenAI.\nOther Planned Uses of Capital\nWe will continue to invest in sales, marketing, product support infrastructure, and existing and advanced areas of technology, as well as acquisitions that align with our business strategy. Additions to property and equipment will continue, including new facilities, datacenters, and computer systems for research and development, sales and marketing, support, and administrative staff. We will continue to invest in capital expenditures to support growth in our cloud offerings and our investments in AI infrastructure and training. We have operating and finance leases for datacenters, corporate offices, research and development facilities, Microsoft Experience Centers, and certain equipment. We have not engaged in any related party transactions or arrangements with unconsolidated entities or other persons that are reasonably likely to materially affect liquidity or the availability of capital resources.\nRefer to Note 1 – Accounting Policies of the Notes to Financial Statements (Part II, Item 8 of this Form 10-K)."

In [ ]:
modified_text = clean_mda_narrative(text)

In [ ]:
modified_text

In [ ]:
filings.obj().reports

In [ ]:
with open("./10_Q.txt", "w") as file:
    file.write(filings.obj()['Item 2'])

# filings.obj()['Item 2']

In [ ]:
for f in filings:
    print(f.parse())
    
    print(f.filing_date, f.form)

In [ ]:
sections = filings.sections()

In [ ]:
sections

In [ ]:


# Required for SEC EDGAR access


def clean_tabular_noise(text):
    """Strips lines that are likely dense tables or numeric noise."""
    if not text: return ""
    lines = str(text).split('\n')
    # Filter out lines that have 4 or more numeric/financial symbols
    cleaned_lines = [line for line in lines if len(re.findall(r'\d|\$|%', line)) < 4]
    return " ".join(cleaned_lines).strip()

def ingest_sec_data(ticker="MSFT", years=5):
    """Fetches and cleans 10-K, 10-Q, and 8-K filings."""
    end_date = datetime(2026, 4, 20)
    start_date = end_date - timedelta(days=years*365)
    date_range = f"{start_date.strftime('%Y-%m-%d')}:{end_date.strftime('%Y-%m-%d')}"
    
    company = Company(ticker)
    # Fetching 8-K is crucial for real-time volatility triggers
    filings = company.get_filings(form=["10-K", "10-Q", "8-K"], filing_date=date_range)
    
    processed_docs = []
    for f in filings:
        try:
            doc = f.obj()
            entry = {"date": f.filing_date, "form": f.form, "accession": f.accession_number}
            
            # Using bracket notation to avoid AttributeError in TenQ
            if f.form == "10-K":
                entry["mda"] = doc['Item 7']
                entry["risk_factors"] = doc['Item 1A']
                entry["business_info"] = doc['Item 1'] # Future RAG context
            elif f.form == "10-Q":
                entry["mda"] = doc['Part I, Item 2'] # Fixed key for TenQ
                entry["risk_factors"] = doc['Part II, Item 1A']
            elif f.form == "8-K":
                entry["mda"] = f.text() # 8-Ks are often unstructured press releases
            
            # Apply tabular cleaning immediately
            entry["mda_clean"] = clean_tabular_noise(entry.get("mda", ""))
            entry["risk_clean"] = clean_tabular_noise(entry.get("risk_factors", ""))
            
            processed_docs.append(entry)
        except Exception as e:
            print(f"Error parsing {f.accession_number} ({f.form}): {e}")
            
    return pd.DataFrame(processed_docs)

def ingest_market_data(ticker="MSFT", years=5):
    """Fetches daily price data and the 10-Year Treasury yield."""
    tickers = [ticker, "^TNX", "^VIX"] # MSFT, 10Y Yield, and Volatility Index
    data = yf.download(tickers, start="2021-01-01", end="2026-04-20")
    
    # Flatten multi-index columns for easier SQL ingestion
    data.columns = ['_'.join(col).strip() for col in data.columns.values]
    return data.reset_index()

In [ ]:
sec_data  = ingest_sec_data(years=1)

In [40]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS transcripts (
    transcript_id TEXT PRIMARY KEY,
    ticker TEXT,
    event_timestamp TEXT,
    effective_date TEXT,
    fiscal_year INTEGER,
    fiscal_period TEXT,
    content_prepped TEXT,
    content_qa TEXT,
    sentiment_score REAL DEFAULT 0.0
)
""")

In [42]:
import earningscall
from datetime import datetime, timedelta
import json
# --- HARD CONSTANTS ---
START_DATE = datetime(2019, 1, 1)
END_DATE = datetime(2026, 4, 22) # Current Date
def process_msft_history(cursor, ticker="MSFT"):
    company = earningscall.get_company(ticker)
    
    # 1. Define the 5-year boundary
    
    # Storage for all processed quarters
    historical_data = []

    # 2. Iterate through events
    for event in company.events():
        # Skip future events
        event_date = event.conference_date.replace(tzinfo=None)
        if not (START_DATE <= event_date <= END_DATE):
            continue

        # 2. EFFECTIVE MARKET DATE (T+1 Logic)
        # If call is 4:00 PM (16:00) or later, the market reacts the NEXT day
        # if event.conference_date.hour >= 16:
        effective_date = (event.conference_date + timedelta(days=1)).strftime('%Y-%m-%d')
        # else:
            # effective_date = event.conference_date.strftime('%Y-%m-%d')
        print(f"Ingesting: Q{event.quarter} {event.year} (Date: {event.conference_date.strftime('%Y-%m-%d')})")
        
        # 3. FISCAL ALIGNMENT
        # We use the library's year/quarter as the "Source of Truth" for labeling
        f_year = event.year
        f_period = f"Q{event.quarter}" if event.quarter < 4 else "FY"
        t_id = f"{ticker}_{f_year}_{f_period}_TRANSCRIPT"
        
        try:
            # Fetch Level 2 to get speaker names and text
            transcript = company.get_transcript(event=event, level=2)
            
            if not transcript or not transcript.speakers:
                continue

            # 3. Apply the split logic to create our lists of dicts
            prepped, qa = split_transcript_by_turns(transcript.speakers)
            
            # Store results with metadata for the training table
            historical_data.append((t_id,
                ticker,
                event.conference_date.strftime('%Y-%m-%d %H:%M:%S'), # Real Timestamp
                effective_date,                                      # Trading Day 0
                f_year,
                f_period,
                json.dumps(prepped),
                json.dumps(qa)))

        except Exception as e:
            print(f"Error processing Q{event.quarter} {event.year}: {e}")
        
        if historical_data:
            
            cursor.executemany("""
                INSERT OR REPLACE INTO transcripts 
                (transcript_id, ticker, event_timestamp, effective_date, fiscal_year, fiscal_period, content_prepped, content_qa) 
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """, historical_data)
        print(f"\n✅ Total Ingested: {len(historical_data)} filings.")
        conn.commit()
    return historical_data

def split_transcript_by_turns(turns):
    """
    Processes Level 2 turns into two lists of dictionaries based on the Q&A pivot.
    """
    prepped_list = []
    qa_list = []
    is_qa_started = False
    
    # MSFT specific pivot markers
    qa_markers = ["q and a", "q&a","q and a"]

    for turn in turns:
        speaker_name = turn.speaker_info.name if turn.speaker else "Unknown"
        speaker_title = turn.speaker_info.title if turn.speaker else "Unknown" 
        text = turn.text if turn.text else ""
        text_lower = text.lower()

        # Detect transition
        if not is_qa_started:
            if any(marker in text_lower for marker in qa_markers):
                is_qa_started = True
                # We skip the specific turn that announces the Q&A to keep data clean
                continue 

        # Add to respective list as a dictionary
        entry = {"speaker_name": speaker_name,'speaker_title':speaker_title, "text": text}
        
        if is_qa_started:
            qa_list.append(entry)
        else:
            prepped_list.append(entry)

    return prepped_list, qa_list

# Execute
msft_dataset = process_msft_history(cursor)

Ingesting: Q2 2026 (Date: 2026-01-28)

✅ Total Ingested: 1 filings.
Ingesting: Q1 2026 (Date: 2025-10-29)

✅ Total Ingested: 2 filings.
Ingesting: Q4 2025 (Date: 2025-07-30)

✅ Total Ingested: 3 filings.
Ingesting: Q3 2025 (Date: 2025-04-30)

✅ Total Ingested: 4 filings.
Ingesting: Q2 2025 (Date: 2025-01-29)

✅ Total Ingested: 5 filings.
Ingesting: Q1 2025 (Date: 2024-10-30)

✅ Total Ingested: 6 filings.
Ingesting: Q4 2024 (Date: 2024-07-30)

✅ Total Ingested: 7 filings.
Ingesting: Q3 2024 (Date: 2024-04-25)

✅ Total Ingested: 8 filings.
Ingesting: Q2 2024 (Date: 2024-01-30)

✅ Total Ingested: 9 filings.
Ingesting: Q1 2024 (Date: 2023-10-24)

✅ Total Ingested: 10 filings.
Ingesting: Q4 2023 (Date: 2023-07-25)

✅ Total Ingested: 11 filings.
Ingesting: Q3 2023 (Date: 2023-04-25)

✅ Total Ingested: 12 filings.
Ingesting: Q2 2023 (Date: 2023-01-24)

✅ Total Ingested: 13 filings.
Ingesting: Q1 2023 (Date: 2022-10-25)

✅ Total Ingested: 14 filings.
Ingesting: Q4 2022 (Date: 2022-07-26)

✅ Total Ingested: 15 filings.
Ingesting: Q3 2022 (Date: 2022-04-26)

✅ Total Ingested: 16 filings.
Ingesting: Q2 2022 (Date: 2022-01-25)

✅ Total Ingested: 17 filings.
Ingesting: Q1 2022 (Date: 2021-10-26)

✅ Total Ingested: 18 filings.
Ingesting: Q4 2021 (Date: 2021-07-27)

✅ Total Ingested: 19 filings.
Ingesting: Q3 2021 (Date: 2021-04-29)

✅ Total Ingested: 20 filings.
Ingesting: Q2 2021 (Date: 2021-01-26)

✅ Total Ingested: 21 filings.
Ingesting: Q1 2021 (Date: 2020-10-27)

✅ Total Ingested: 22 filings.
Ingesting: Q4 2020 (Date: 2020-07-22)

✅ Total Ingested: 23 filings.
Ingesting: Q3 2020 (Date: 2020-04-29)

✅ Total Ingested: 24 filings.
Ingesting: Q2 2020 (Date: 2020-01-29)

✅ Total Ingested: 25 filings.
Ingesting: Q1 2020 (Date: 2019-10-23)

✅ Total Ingested: 26 filings.
Ingesting: Q4 2019 (Date: 2019-07-18)

✅ Total Ingested: 27 filings.
Ingesting: Q3 2019 (Date: 2019-04-24)

✅ Total Ingested: 28 filings.
Ingesting: Q2 2019 (Date: 2019-01-30)

✅ Total Ingested: 29 filings.

In [ ]:
msft_dataset

In [ ]:
def initialize_transcript_tables(client):
    # Table A: Metadata
    client.execute('''
        CREATE TABLE IF NOT EXISTS earnings_calls (
            call_id TEXT PRIMARY KEY,
            ticker TEXT,
            date TEXT,
            year INTEGER,
            quarter INTEGER
        )
    ''')
    
    # Table B: Individual Speech Acts
    client.execute('''
        CREATE TABLE IF NOT EXISTS call_transcript_turns (
            turn_id TEXT PRIMARY KEY,
            call_id TEXT,
            section TEXT,       -- 'PREP' or 'QA'
            sequence INTEGER,   -- The order of speaking
            speaker TEXT,
            content TEXT,
            sentiment_score REAL DEFAULT 0.0
        )
    ''')
    

def sync_transcripts_to_turso(ticker, transcripts_list):
    """
    transcripts_list: Your [dict, dict, ...] from the previous step
    """
    initialize_transcript_tables()
    
    call_rows = []
    turn_rows = []
    
    for call in transcripts_list:
        call_id = f"{ticker}_{call['year']}_Q{call['quarter']}"
        
        # 1. Add to Metadata
        call_rows.append((call_id, ticker, call['date'], call['year'], call['quarter']))
        
        # 2. Add Prepared Remarks (Section: PREP)
        for i, (speaker, text) in enumerate(call['prepped_text']):
            turn_id = f"{call_id}_PREP_{i}"
            turn_rows.append((turn_id, call_id, 'PREP', i, speaker, text, 0.0))
            
        # 3. Add Q&A Section (Section: QA)
        for i, (speaker, text) in enumerate(call['qa']):
            turn_id = f"{call_id}_QA_{i}"
            turn_rows.append((turn_id, call_id, 'QA', i, speaker, text, 0.0))

    # Batch Insert (Production Style)
    cursor.executemany("INSERT OR REPLACE INTO earnings_calls VALUES (?, ?, ?, ?, ?)", call_rows)
    cursor.executemany("INSERT OR REPLACE INTO call_transcript_turns VALUES (?, ?, ?, ?, ?, ?, ?)", turn_rows)
    
    conn.commit()
    print(f"✅ Synced {len(call_rows)} calls and {len(turn_rows)} individual speech turns.")

# EXECUTE
# sync_transcripts_to_turso('MSFT', my_transcripts_list)

In [ ]:
import sys
print(sys.version)

In [ ]:
dat = yf.Ticker("MSFT")

In [ ]:
dat.info()